blog_site/blog/urls.py
from django.urls import path, re_path
import blog.views as blog_view
import users.views as users_view
from django.conf import settings
from django.conf.urls.static import static

app_name = "blog"

urlpatterns = [
    path("about/", blog_view.blog_about, name="about"),
    path("new_post", blog_view.new_post, name="new_post"),
    path("update/<int:s_no>", blog_view.edit_post, name="update"),
    path("delete/<int:s_no>", blog_view.delete_post, name="delete"),
    path("allposts/", blog_view.allpost_view, name="view_more"),
    # re_path(r'^blog/(?P<slug>[0-9]+)/$',blog_view.post_update,name='post_update'),
    # path('post_update', blog_view.post_update, name='post_update'),
    path("blog/<str:slug>", blog_view.post_detail, name="post_detail"),
    path("blog/<str:slug>/comment", blog_view.post_comment, name="post_comment"),
    path("edit_profile/<int:id>", users_view.edit_profile, name="edit_profile"),
]
if True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog_site/blog_site/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
import users.views as users_view
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include("blog.urls")),
    path("", include("home.urls")),
    re_path(r"^tinymce/", include("tinymce.urls")),
    path("admin/", admin.site.urls),
    path("register/", users_view.register_view, name="register"),
    path("signin/", users_view.signin_view, name="signin"),
    path("logout/", users_view.logout_view, name="logout"),
    path("profile/", users_view.profile, name="profile"),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog_site/blog/models.py
from blog.slug import slugify
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField
from PIL import Image

# Create your models here.


class Post(models.Model):
    s_no = models.AutoField(primary_key=True)
    title = models.CharField(max_length=500)
    subtitle = models.CharField(max_length=500)
    post_image = models.ImageField(
        upload_to='upload_images/', default='post_image.jpg')
    content = HTMLField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=130, null=False, unique=True)
    timeStamp = models.DateTimeField(blank=True, default=timezone.now())

    def __str__(self):
        return self.title + ' by ' + self.author.first_name + f' ({self.s_no})'

    def save(self, **kwargs):
        slug = '%s' % (self.title)
        self.slug = slugify(self, slug)
        super(Post, self).save()


class Comment(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=500)

blog_site/blog/forms.py
from django.http import Http404
from django import forms
from blog.models import Post, Comment


class BlogPostForm(forms.ModelForm):
    subtitle = forms.CharField(required=False)

    class Meta:
        model = Post
        fields = ['title', 'subtitle', 'post_image', 'content']


class BlogUpdateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'subtitle', 'post_image', 'content']

class CommentForm(forms.ModelForm):
    model = Comment
    fields = ['user', 'comment']

blog_site/blog/views.py
import random
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Post
from django.contrib import messages
from .forms import BlogPostForm, BlogUpdateForm, CommentForm

@login_required(login_url='home/signin')
def new_post(request):
    if request.method != 'POST':
        form = BlogPostForm()
    else:
        form = BlogPostForm(request.POST, request.FILES)
        print(form.is_valid())
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('/')
    return render(request, 'blog/new_form.html',{'form':form})

def allpost_view(request):
    allblog = Post.objects.all()[:18]
    context = {'allblog': allblog}
    return render(request, 'blog/allblog.html', context)

@login_required(login_url='home/signin')
def post_detail(request,slug):
    context = {}
    post = Post.objects.get(slug=slug)
    context = {'post':post}
    return render(request, 'blog/post_detail.html', context)
   
@login_required(login_url='home/signin')
def edit_post(request,s_no):
    post = Post.objects.get(s_no=s_no)
    if request.method != 'POST':
        form = BlogUpdateForm(instance=post)
    else:
        form = BlogUpdateForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            post.author = request.user
            messages.success(request, 'Post Updated Successfully!')
            return redirect('/')
    context={'post':post, 'form':form}
    return render(request, 'blog/post_update_form.html', context)

@login_required(login_url='home/signin')
def delete_post(request, s_no):
    post = get_object_or_404(Post,s_no=s_no)
    post.delete()
    messages.success(request, 'Post Deleted Successfully!')
    return redirect('/')

def post_comment(request):
    if request.method != 'Post':
        form = CommentForm()
    else:
        form = CommentForm(request.Post)
        if form.is_valid():
            form.save()
            return redirect()
    context = {'form':form}
    return render(request, 'blog/post_detail.html', context)



@login_required(login_url='home/signin')  
def blog_about(request):
    return render(request, 'blog/about.html')

blog_site/blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}


{% include "blog/nav.html" %}
<section class="py-lg-8 py-md-10 px-md-5" style="background-color: #ebeef0;">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 col-12 m-auto p-4">
                <div class="flex">
                    <h2 class="text uppercase text-center">About Us</h2>
                </div>
            </div>
            <div class="container d-flex px-4">
                <div class="row col-lg-10 mx-auto">
                    <div>
                        My AeroGarden hydroponic garden sits on the countertop in my house. You might think that would
                        mean
                        it would never have bugs on it, but you’d be wrong.

                        For some reason, my basil seems to constantly attract aphids. The first time I saw them, I had
                        no
                        idea what they were, and I had to do a lot of searching on the Internet to figure it out.

                        This morning, when I realized my basil had aphids on it again, I wondered if Bard could diagnose
                        the
                        problem. I gave Bard a simple picture of a leaf of the plant and asked it to describe what it
                        saw.
                        For some reason, my basil seems to constantly attract aphids. The first time I saw them, I had
                        no
                        idea what they were, and I had to do a lot of searching on the Internet to figure it out.

                        This morning, when I realized my basil had aphids on it again, I wondered if Bard could diagnose
                        the
                        problem. I gave Bard a simple picture of a leaf of the plant and asked it to describe what it
                        saw.
                    </div>
                    <div>
                        My AeroGarden hydroponic garden sits on the countertop in my house. You might think that would
                        mean
                        it would never have bugs on it, but you’d be wrong.

                        For some reason, my basil seems to constantly attract aphids. The first time I saw them, I had
                        no
                        idea what they were, and I had to do a lot of searching on the Internet to figure it out.

                        This morning, when I realized my basil had aphids on it again, I wondered if Bard could diagnose
                        the
                        problem. I gave Bard a simple picture of a leaf of the plant and asked it to describe what it
                        saw.
                        For some reason, my basil seems to constantly attract aphids. The first time I saw them, I had
                        no
                        idea what they were, and I had to do a lot of searching on the Internet to figure it out.

                        This morning, when I realized my basil had aphids on it again, I wondered if Bard could diagnose
                        the
                        problem. I gave Bard a simple picture of a leaf of the plant and asked it to describe what it
                        saw.

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

blog_site/blog/templates/blog/allblog.html
{% extends 'blog/base.html' %}
{% block content %}

{% include 'blog/nav.html' %}

{% load static %}
<section class="py-lg-8 py-md-10 px-md-5" style="background-color: #ebeef0;">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div>
                    <h2>All Post</h2>
                </div>
            </div>
            <div class="container d-flex">
                <div class="row row-cols-1 row-cols-md-3">
                    {% for post in allblog %}
                    {% if user.is_authenticated %}
                    <div class="col-12 col-md-4 card-post">
                        <div class="" style="padding: 8px;">
                            <a href="../blog/{{post.slug}}" class="image-hover img-zoom-in">
                                <img src="{{post.post_image.url}}" height="225px" width="425px"
                                    class="card-img-top rounded-3" alt="...">
                            </a>
                            <div class="card-content">
                                <div class="card-authors">
                                    <div class="author">
                                        <div class="author-image">
                                            <a href="/profile/">
                                                <img src="{{post.author.profile.profile_image.url}}" alt="...">
                                            </a>
                                        </div>
                                        <div class="author-content">
                                            <div class="author-name">{{post.author.first_name}}</div>
                                            <div class="author-date">{{post.timeStamp.date}}</div>
                                        </div>
                                    </div>
                                </div>
                                <h5 class="my-3"> <a class="heading" href="../blog/{{post.slug}}">{{ post.title }}</a>
                                </h5>
                                <p class="my-2">{{post.subtitle | truncatechars:100}}</p>
                            </div>
                        </div>
                    </div>
                    {% else %}
                    <div class="col-12 col-md-4 card-post">
                        <div class="" style="padding: 8px;">
                            <a href="{% url 'signin' %}" class="image-hover img-zoom-in">
                                <img src="{{post.post_image.url}}" height="225px" width="425px"
                                    class="card-img-top rounded-3" alt="...">
                            </a>
                            <div class="card-content">
                                <div class="card-authors">
                                    <div class="author">
                                        <div class="author-image">
                                            <a href="">
                                                <img src="{{post.author.profile.profile_image.url}}" alt="...">
                                            </a>
                                        </div>
                                        <div class="author-content">
                                            <div class="author-name">{{post.author.first_name}}</div>
                                            <div class="author-date">{{post.timeStamp.date}}</div>
                                        </div>
                                    </div>
                                </div>
                                <h5 class="my-3"> <a class="heading" href="{% url 'signin' %}">{{ post.title }}</a></h5>
                                <p class="my-2">{{ post.subtitle }}</p>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

blog_site/blog/templates/blog/base.html
{% load static %}

<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Saga</title>
    <!-- bootstrap css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">

    <!-- bootstrap icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">

    <!-- fonts -->
    <link
        href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
        rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css2?family=Bree+Serif&display=swap" rel="stylesheet">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/form.css' %}">

    <!-- text editor js -->
    <script src="https://cdn.tiny.cloud/1/eo55g68u1wu49qi1muggl293r63fqw0sf08y25s0mncrsh2t/tinymce/6/tinymce.min.js"
        referrerpolicy="origin"></script>
</head>

<body>
    {% block content %}
    {% endblock content %}

    <!-- text editor js -->
    <script>
        const MediumTitleConfig = {
            selector: '#title',
            menubar: false,
            toolbar: false,
            statusbar: false,
            plugins: 'advlist autolink lists link image charmap preview anchor pagebreak',
            inline: true,
            skin: 'snow',
            icons: 'thin',
            content_style:
                "@import url('https://fonts.googleapis.com/css2?family=Tinos&display=swap'); body { font-family: 'Tinos', serif; font-size: 16pt; color: #292929; }",
            placeholder: "Title",

        }
        const MediumStoryConfig = {
            selector: '#editor',
            manubar: false,
            statusbar: false,
            toolbar_mode: 'floating',
            toolbar: false,
            plugins: 'advlist autolink lists link image media table hr charmap preview anchor pagebreak quickbars',
            skin: 'snow',
            icons: 'thin',
            content_style:
                "@import url('https://fonts.googleapis.com/css2?family=Tinos&display=swap'); body { font-family: 'Tinos', serif; font-size: 16pt; color: #292929; }",
            placeholder: "Tell your story...",
            // quickbars_insert_toolbar: "image media table hr",
            quickbars_selection_toolbar: "bold italic link | h1 h2 | blockquote",
        };

        tinymce.init(MediumTitleConfig);
        tinymce.init(MediumStoryConfig);
        tinymce.init({
            quickbars_selection_toolbar: "bold italic link | h1 h2 | blockquote",
        });
        tinymce.init({
            quickbars_insert_toolbar: "image media table hr",
        });

    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery.min.js"></script>
    <script src="{% static 'home/js/form.js' %}"></script>
    <script src="{% static 'blog/js/tinymce/custom.js' %}"></script>
</body>

</html>

blog_site/blog/templates/blog/nav.html
<div class="header font-fam">
    <nav class="navbar navbar-expand-lg fixed-top" style="background-color: #ffffff;">
        <div class="container-fluid col-8">
            <a class="navbar-brand fs-4 fw-bold" href="/">Saga</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav col-lg-10 justify-content-end">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" href="/about/">About</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'signin' %}">About</a>
                    </li>
                    {% endif %}
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'blog:new_post' %}"><i class="bi bi-pencil-square"
                                style="margin-right: 4px;"></i>Write</a>
                    </li>
                    <li class="nav-item">
                        {% else %}
                        <a class="nav-link active" href="{% url 'signin' %}"><i class="bi bi-pencil-square"
                                style="margin-right: 4px;"></i>Write</a>
                    </li>
                    {% endif %}
                </ul>
                {% if user.is_authenticated %}
                <ul class="navbar-nav logout-btn justify-content-end">
                    <!-- <a class=" nav-link active" href="">Logout</a> -->
                    <li class="nav-item dropdown h4 pt-2">
                        {% if user.profile.profile_image.url %}
                        <a class="nav-link active dropdown-toggle text-secondary" href="#" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            <img class="rounded-5" src="{{user.profile.profile_image.url}}" height="32px" width="32px"
                                alt="{{ user.first_name }}">
                        </a>
                        {% else %}
                        <a class="nav-link active dropdown-toggle text-secondary" href="#" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-person-circle"></i> </a>
                        {% endif %}
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="">{{user.first_name}}</a></li>
                            <hr class="dropdown-divider">
                            <li><a class="dropdown-item" href="/profile/">Profile</a></li>
                            <li><a class="dropdown-item" href="#">Contact Us</a></li>
                            <li>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                        </ul>
                    </li>
                </ul>
                {% else %}
                <ul class="navbar-nav col-1 col-lg-3">
                    <a class="nav-link active" href="{% url 'signin' %}">SignIn</a>
                    <button class="btn btn-sm btn-outline-success m-1" style="border-radius: 20px; width: 120px;"
                        type="submit"><a class="signup" href="{% url 'register' %}"> Get
                            Started</a>
                </ul>
                {% endif %}
            </div>
        </div>
    </nav>
</div>

blog_site/blog/templates/blog/new_form.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
{% include 'blog/nav.html' %}
<section class="py-lg-8 py-md-10 py-sm-10 mh-100" style="background-color: #ebeef0bf;">
    <div class="container p-4">
        <div class="row rounded-1" style="background-color: #ebeef0;">
            <div class="col-lg-10 col-12 m-auto p-4">
                <div class="flex">
                    <h2 class="text uppercase text-center">New Post</h2>
                </div>
                <form action="/new_post" enctype='multipart/form-data' method="POST">
                    {% csrf_token %}
                    <div class="form-outline">
                        <label for="form-label">
                            <h1></h1>
                        </label>
                        <input type="text" name="title" id="title" class="form-control-lg" placeholder="Title">
                    </div>
                    <div class="form-outline">
                        <label for="form-label">
                            <h3></h3>
                        </label>
                        <input type="text" name="subtitle" id="subtitle" class="form-control-lg" placeholder="Subtitle">
                    </div>
                    <div class="form-outline d-flex mt-5">
                        <label class="form-label" for="post_image" style="font-size: 40px;font-weight: bold;
                        font-family: Tinos, serif; padding: 2px 2px 2px 24px; color: rgba(34, 47, 62, 0.232);
                            ">Image</label>
                        <input type="file" name="post_image" accept="image/*"
                            class="form-control form-control-sm mx-auto col-2" id="post_image"
                            style="width:50%; background-color: transparent;padding: 1.5rem 0.5rem; border: 0.5px solid #80808000;" />
                    </div>
                    <div class="form-outline">
                        <div class="form-group">
                            <label for="form-group">
                            </label>
                            <textarea class="form-control form-control-lg" name="content" id="editor" rows="10"
                                placeholder="Tell your story..." data-error="Please, leave us a message."></textarea>
                        </div>
                        <div class="my-3 d-flex justify-content-center">
                            <button class="btn btn-secondary btn-sm btn-block rounded-5"
                                style="width: 20%;">POST</button>
                        </div>
                    </div>
            </div>
            </form>
        </div>
    </div>
    </div>

</section>
{% endblock content %}

blog_site/blog/templates/blog/post_update_form.html
{% extends 'blog/base.html' %}
{% load static %}

{% block content %}
{% include 'blog/nav.html' %}
<section class="py-lg-8 py-md-10 py-sm-10 mh-100" style="background-color: #ebeef0bf;">
    <div class="container p-4">
        <div class="row rounded-1" style="background-color: #ebeef0;">
            <div class="col-lg-10 col-12 m-auto p-4">
                <div class="flex">
                    <h2 class="text uppercase text-center">Update Post</h2>
                </div>
                <form action="" enctype='multipart/form-data' method="POST">
                    {% csrf_token %}
                    <div class="form-outline"><label class="form-label" for="" style="font-family: Tinos, serif; padding: 2px 2px 2px 24px; color: rgba(34, 47, 62, 0.232);
                        ">Title</label>
                        <label for="form-label">
                            <h1></h1>
                        </label>
                        <input type="text" name="title" id="title" value="{{ post.title }}" class="form-control-lg"
                            placeholder="Title">
                    </div>
                    <div class="form-outline"><label class="form-label" for="" style="font-family: Tinos, serif; padding: 2px 2px 2px 24px; color: rgba(34, 47, 62, 0.232);
                        ">Subtitle</label>
                        <label for="form-label">
                            <h3></h3>
                        </label>
                        <input type="text" name="subtitle" id="subtitle" value="{{ post.subtitle }}"
                            class="form-control-lg" placeholder="Subtitle">
                    </div>
                    <div class="form-outline d-flex mt-5">
                        <label class="form-label" for="" style="font-size: 20px;font-weight: 200;
                        font-family: Tinos, serif; padding: 2px 2px 2px 24px; color: rgba(34, 47, 62, 0.232);
                            ">Image</label>
                        <input type="file" name="post_image" src="{{ post.post_image.url}}"
                            class="form-control form-control-sm mx-auto col-2" id="post_image"
                            style="width:50%; background-color: transparent;padding: 0.5rem 0.5rem; border: 0.5px solid #80808000;" />
                    </div>
                    <div class="form-outline d-flex mt-5">
                        <label class="form-label" for="" style="font-family: Tinos, serif; padding: 2px 2px 2px 24px; color: rgba(34, 47, 62, 0.232);
                            ">Current Image</label>
                        <a class="mx-auto text-primary" style="width: 54%; word-wrap: break-word;"
                            href="{{post.post_image.url}}">{{post.post_image}}</a>
                    </div>
                    <div class="form-outline">
                        <div class="form-group">
                            <label for="form-group">
                            </label>
                            <textarea class="form-control form-control-lg" name="content" id="editor" rows="10"
                                placeholder="Tell your story..."
                                data-error="Please, leave us a message.">{{post.content | safe}}</textarea>
                        </div>
                        <div class="my-3 d-flex justify-content-center">
                            <button class="btn btn-secondary btn-sm btn-block rounded-5">UPDATE
                                POST</button>
                        </div>
                    </div>
            </div>
            </form>
        </div>
    </div>
    </div>

</section>
{% endblock content %}

blog_site/blog/templates/blog/subscription_form.html
<!--subscription -->
<section class="py-lg-8 py-md-10 px-md-5" style="background-color: #ebeef0;">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="subscribe">
                    <div class="row p-2">
                        <div class="col-12 col-md-4 mb-2 mb-md-0">
                            <h2 class="">Let's keep in touch</h2>
                        </div>
                        <div class="co-12 col-md-8">
                            <div id="mc_embed_signup">
                                <form action="#" method="" id="mc-embedded-subscribe-form"
                                    name="mc-embedded-subscribe-form" class="subscribe-form" target="_blank"
                                    novalidate="novalidate">
                                    <div class="subscribe-fields d-flex px-2">
                                        <input class="required email container-sm rounded-5" id="mce-EMAIL" name="EMAIL"
                                            placeholder="Your email address" type="email" value="" aria-required="true"
                                            style="width: 60%;">
                                        <div aria-hidden="true" style="position: absolute; left: -5000px">
                                            <input name="b_675276692aebec1c007f8156d_3e3da720c2" tabindex="-1"
                                                type="text" value="">
                                        </div>
                                        <button class="btn btn-lg btn-danger mx-3 mt-2"
                                            style="border-radius: 25px; width: 130px; height: 50px;"
                                            type="button">Submit</button>
                                    </div>
                                    <div class="subscribe-responses" id="mce-responses">
                                        <div class="response response-error" id="mce-error-response"
                                            style="display: none"></div>
                                        <div class="response response-success" id="mce-success-response"
                                            style="display: none"></div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>